### ISSUE TITLE
MySQL storage

### ISSUE THREAD

**Issue by nmsa** [eubr-atmosphere/tma-framework-m#14]
After #11, #13 
- [x] Define datamodel / crebas.sql 
- [x] Create example data

**Comment by nmsa** [comment]
Datamodel created in 
https://github.com/eubr-atmosphere/tma-framework/pull/5

**Comment by joseadp** [comment]
@nmsa , the example data was created in the knowledge repository according to the issue https://github.com/eubr-atmosphere/tma-framework-k/issues/4
Can we close this issue? (cc @rfrsilva )

**Comment by nmsa** [comment]
Where can I find the data?

**Comment by joseadp** [comment]
@nmsa , https://github.com/eubr-atmosphere/tma-framework-k/blob/new/db_development/development/mysql/example_data_mysql.sql
