### ISSUE TITLE
Create tool to input Design-time data

### ISSUE THREAD

**Issue by nmsa** [eubr-atmosphere/tma-framework-m#19]
As described in the [TMA Framework](https://github.com/nmsa/tma-framework):

> The platform also receives the results of the design-time assessment tasks, in which the performance and scalability requirements are not so stringent. The tools used to perform these assessment tasks are able to push data through the ReceiveData interface. When this not possible, adapters are used to transform the output of the tools and submit it to the platform. In some cases these results may have to be added manually, through a supporting tool.

**Comment by joseadp** [comment]
This issue was completed with PR #68 (https://github.com/eubr-atmosphere/tma-framework-m/pull/68)
