### ISSUE TITLE
Demonstration of the existing features

### ISSUE THREAD

**Issue by nmsa** [eubr-atmosphere/tma-framework-m#24]
Prepare a video (or slides) of:
- [x] Monitor deployment
- [x] Client usage
- [x] Probe development
- [x] Containers metrics reported

Slides available at: [github.com/eubr-atmosphere/tma-framework/blob/framework-usage/documents/ATMOSPHERE_TMA_Framework_usage.pptx ](https://github.com/eubr-atmosphere/tma-framework/blob/framework-usage/documents/ATMOSPHERE_TMA_Framework_usage.pptx)

**Comment by nmsa** [comment]
@rfrsilva what is the status of the demos?

**Comment by rfrsilva** [comment]
These slides: https://github.com/eubr-atmosphere/tma-framework/blob/framework-usage/documents/ATMOSPHERE_TMA_Framework_usage.pptx cover all topics presented in this issue and are also according to the feedback recently provided.

**Comment by nmsa** [comment]
Great, thanks!
