### ISSUE TITLE
Create Docker Image for Probe Kubernetes Metrics

### ISSUE THREAD

**Issue by rfrsilva** [eubr-atmosphere/tma-framework-m#39]
Create base Docker image for probe Kubernetes Metrics with the same structure of the other existing probes.

**Comment by joseadp** [comment]
Which probe is this issue related to?
- probe-k8-metrics(https://github.com/eubr-atmosphere/tma-framework-m/tree/master/development/probes/probe-k8-metrics): metrics from docker in kubernetes clustes?
- probe-kubernetes-api (https://github.com/eubr-atmosphere/tma-framework-m/tree/master/development/probes/probe-kubernetes-api): metrics from pods/nodes collected from the metrics-server api ?
(@nmsa @rfrsilva)

**Comment by nmsa** [comment]
I think both fit here, but @rfrsilva and/or @jpslopes are the best to explain to you.

**Comment by rfrsilva** [comment]
This issue is related to probe-k8-metrics.
