### ISSUE TITLE
Monitor Testing Mode Instructions in Wiki

### ISSUE THREAD

**Issue by nmsa** [eubr-atmosphere/tma-framework-m#43]
@rfrsilva, please add/link the config instructions in the wiki:
https://github.com/eubr-atmosphere/tma-framework/wiki/Deploy-a-testing-mode-TMA-Monitor-in-kubernetes

**Comment by rfrsilva** [comment]
https://github.com/eubr-atmosphere/tma-framework/wiki/Testing-mode-TMA-Monitor-deployment-in-Kubernetes
Any changes?

**Comment by nmsa** [comment]
Just did minor changes to the link and the content.
Looks good now.
